# Generated by Django 3.2.16 on 2023-01-22 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_alter_data_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxValueValidator(19)]),
        ),
    ]
