# Generated by Django 3.2.16 on 2023-01-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_alter_data_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
